# Generated by Django 2.2.6 on 2019-10-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='lambda_f',
        ),
        migrations.RemoveField(
            model_name='event',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.RemoveField(
            model_name='groupuser',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupuser',
            name='user',
        ),
        migrations.RenameField(
            model_name='lambda_f',
            old_name='name',
            new_name='lst',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='GroupUser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
